version: '3.8'

volumes:
  postgres-data:


networks:
  dev:


services:
  app:
    container_name: dev_cont_import_ofx
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_HOSTNAME: db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - dev
    depends_on:
      - db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: postgresdb_ofx
    image: postgres:${POSTGRESQL_VERSION}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_USER}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRESQL_DB},${POSTGRESQL_DB_MS_DATA}
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      # POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      # POSTGRES_USER: ${POSTGRESQL_USER}
      # POSTGRES_DB: ${POSTGRESQL_DB}
      # POSTGRES_MULTIPLE_DATABASES: "${POSTGRESQL_DB}","${POSTGRESQL_DB_KEYCLOAK}"
    networks:
      - dev
    ports:
      - "5777:5432"
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  rabbitmq:
    image: rabbitmq:3.13.3-management-alpine
    container_name: rabbitmq_ofx
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_USER=admin
    volumes:
        - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - dev